apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: twitter-demo
  labels:
    app.kubernetes.io/part-of: twitter-demo
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: twitter-demo
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: twitter-demo
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: twitter-demo
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: stateless
        image: ghcr.io/mhoshi-vm/tap99-demo/twitter-demo-tap-demo@sha256:20f0cc5fe93b4737929c4129fab4f1856ce6eeef8801bc1481e3302716690e1f
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

