apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-demo-stateful
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
  labels:
    app.kubernetes.io/part-of: twitter-demo-stateful
    apps.tanzu.vmware.com/workload-type: tcp
    app.kubernetes.io/component: run
    carto.run/workload-name: twitter-demo-stateful
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: twitter-demo-stateful
      apps.tanzu.vmware.com/workload-type: tcp
      carto.run/workload-name: twitter-demo-stateful
      conventions.apps.tanzu.vmware.com/framework: spring-boot
      services.conventions.apps.tanzu.vmware.com/postgres: workload
      services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
      tanzu.app.live.view: "true"
      tanzu.app.live.view.application.actuator.port: "8081"
      tanzu.app.live.view.application.flavours: spring-boot
      tanzu.app.live.view.application.name: twitter-demo-stateful
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.7.3
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/service-intent-postgres
          spring-boot-convention/service-intent-rabbitmq
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        services.conventions.apps.tanzu.vmware.com/postgres: postgresql/42.3.6
        services.conventions.apps.tanzu.vmware.com/rabbitmq: amqp-client/5.14.2
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: twitter-demo-stateful
        apps.tanzu.vmware.com/workload-type: tcp
        carto.run/workload-name: twitter-demo-stateful
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        services.conventions.apps.tanzu.vmware.com/postgres: workload
        services.conventions.apps.tanzu.vmware.com/rabbitmq: workload
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: twitter-demo-stateful
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: stateful
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: ghcr.io/mhoshi-vm/tap99-demo/twitter-demo-tap-demo@sha256:79cc3a8f431ab92338e7fcb2aed2fa7e7b2b8272c9c3b38c6dc8fff4744bfc6f
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

