apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-demo-stateful
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
  labels:
    app.kubernetes.io/part-of: twitter-demo-stateful
    apps.tanzu.vmware.com/workload-type: tcp
    app.kubernetes.io/component: run
    carto.run/workload-name: twitter-demo-stateful
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: twitter-demo-stateful
      apps.tanzu.vmware.com/workload-type: tcp
      carto.run/workload-name: twitter-demo-stateful
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: twitter-demo-stateful
        apps.tanzu.vmware.com/workload-type: tcp
        carto.run/workload-name: twitter-demo-stateful
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: stateful
        - name: TWITTER_HASH_TAGS
          value: '#hoge'
        image: ghcr.io/mhoshi-vm/tap99-demo/twitter-demo-tap-demo@sha256:549ddf104eac1f48da6732b9aa56b66ac5072fbb61c9d6797c075b4e93b8b392
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

