apiVersion: v1
kind: Service
metadata:
  name: twitter-demo-stateful
  labels:
    app.kubernetes.io/part-of: twitter-demo-stateful
    apps.tanzu.vmware.com/workload-type: tcp
    app.kubernetes.io/component: run
    carto.run/workload-name: twitter-demo-stateful
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: twitter-demo-stateful
    apps.tanzu.vmware.com/workload-type: tcp
    carto.run/workload-name: twitter-demo-stateful
  ports: []

